'use strict';

// Syncthing .stignore writer (Phase B B12).
//
// Generates the `.stignore` content for a syncthing-backed workspace
// so the daemon's Syncthing folder agrees with the Desktop's
// ignore_evaluator about which paths are syncable. Without this,
// Desktop's UI would say a path is "included" while Syncthing's
// transport layer skipped it (or vice versa).
//
// CRITICAL — recipe ordering. Syncthing's .stignore semantics are
// FIRST-MATCH-WINS (gitignore-style ordering, NOT "directory exclusion
// is final"). To re-include children of a denylisted directory, we
// MUST emit the `!` re-includes BEFORE the denylist line. The
// `ignore` npm package's "directory exclusion is final" rule is why
// the matcher uses a separate claw-back predicate (round-1 codex P0
// #1 on the file-tree plan); .stignore needs the inverse: !-prefix-
// first so first-match-wins claws back correctly.
//
// Generated layout:
//
//   # Header (one comment line so .stignore is identifiable as ours)
//   # generated by Kari Desktop — do not edit manually
//
//   # Hard-ignore (ALWAYS at the top — even an "!override" can never
//   # re-include .git/, .kari-engine/, *.kari-incoming. Defense in depth:
//   # the override store also rejects hard-ignore anchors at write.)
//   .git/**
//   .kari-engine/**
//   *.kari-incoming
//   *.tmp.kari-incoming
//   .DS_Store
//   Thumbs.db
//
//   # Project include overrides (file-tree visibility plan, Task 2b).
//   # Per-anchor trio: directory entry + descendants. Trio is needed
//   # because Syncthing won't descend into an excluded directory; the
//   # bare `!anchor` re-includes the entry, `!anchor/**` re-includes
//   # contents, the trailing-slash variant covers matcher-version drift.
//   !node_modules/some-patched-package/
//   !node_modules/some-patched-package
//   !node_modules/some-patched-package/**
//
//   # Lightweight denylist (only in 'lightweight' mode; full mode emits
//   # an empty denylist section). Comes AFTER the re-includes so
//   # first-match-wins keeps the carve-out alive.
//   node_modules/**
//   .pnpm-store/**
//   ...
//
//   # User .kariignore (verbatim, with comments + blanks stripped)
//   secrets/**
//
// Order is load-bearing — first-match-wins means re-includes BEFORE
// denylist, denylist BEFORE .kariignore. Hard-ignore at the very top
// for visibility (its position doesn't actually matter because no
// `!` line above it can re-include hard-ignored paths — the matcher's
// front predicate enforces that — but readers expect the strongest
// rule first).

const crypto = require('node:crypto');
const fsp = require('node:fs/promises');
const path = require('node:path');

const {
  getEffectiveIgnoreLines,
  getHardIgnoreLines,
  isHardIgnored,
} = require('./ignore_evaluator.cjs');

// Windows filesystem errors that mean "transiently locked, try again" rather
// than "permanently denied". Two concurrent writers (e.g. bindAndStartDaemon
// + an override change fired by the UI in the same tick) race on rename and
// on the prior-content read; on POSIX both succeed because the kernel
// serializes, but on Windows defender / file-system caching briefly locks
// the file and the second op returns one of these codes. They are NOT the
// same class of failure round-2 codex #2 was guarding against (permanent
// EACCES from a chmod-protected dir) — those would persist across retries.
const TRANSIENT_FS_CODES = new Set([
  'EBUSY', 'EACCES', 'EPERM', 'EMFILE', 'ENFILE', 'UNKNOWN',
]);

function sleepMs(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function withTransientRetry(op) {
  const backoffs = [5, 10, 25];
  let lastErr = null;
  for (let attempt = 0; attempt <= backoffs.length; attempt++) {
    try {
      return await op();
    } catch (err) {
      lastErr = err;
      if (!err || !TRANSIENT_FS_CODES.has(err.code) || attempt === backoffs.length) {
        throw err;
      }
      await sleepMs(backoffs[attempt]);
    }
  }
  throw lastErr;
}

// Normalize an override anchor the same way sync_override_store does.
// We can't `require('./sync_override_store.cjs').normalizeRelPath`
// without pulling Electron's app dependency into this module, so we
// inline the normalization. CONTRACT: identical output to
// sync_override_store.normalizeRelPath (round-1 codex on FT-Task-2b
// hardened both to reject `..` segments before path.posix.normalize
// collapses them).
function normalizeAnchor(value) {
  if (typeof value !== 'string') return null;
  let s = value.replace(/\\/g, '/');
  if (s.startsWith('/')) return null;
  for (const seg of s.split('/')) {
    if (seg === '..') return null;
  }
  s = path.posix.normalize(s);
  while (s.startsWith('./')) s = s.slice(2);
  while (s.length > 1 && s.endsWith('/')) s = s.slice(0, -1);
  if (s.length === 0 || s === '.' || s === '..') return null;
  return s;
}

// Render the three !-lines per override anchor that Syncthing needs
// to (a) re-include the directory entry so it descends, AND (b)
// re-include the contents. Files (anchor with extension) only need
// the bare !anchor form, but emitting the dir variants is harmless
// (Syncthing pattern matcher tolerates extra rules that never match).
function renderAnchorOverrideLines(anchor) {
  return [
    `!${anchor}/`,
    `!${anchor}`,
    `!${anchor}/**`,
  ];
}

// Gitignore-to-Syncthing pattern translation (round-1 codex #1 on B12).
// Both formats look similar but interpret trailing slashes oppositely:
//
//   gitignore  `name/`  → directory entry + contents
//   syncthing  `name/`  → contents only; the `name` entry itself stays syncable
//
// ignore_evaluator emits gitignore-style patterns (the `ignore` npm package
// is the authority). Without translation, .git/ in our hard-ignore would
// leave the bare `.git` directory entry syncable on the Syncthing side
// even though the matcher's front predicate rejects everything under it
// — exact matcher/transport divergence B12 exists to prevent.
//
// Translation: strip the trailing `/` so the pattern becomes a bare name
// that Syncthing matches at any depth (per its docs: a pattern with no
// slash matches at any directory depth). Negation `!` prefix preserved.
// Patterns with embedded `/` are paths Syncthing matches from root —
// passed through unchanged.
function toStignoreForm(gitignorePattern) {
  let p = String(gitignorePattern);
  if (p.length === 0) return p;
  // Preserve negation prefix during the transform.
  let neg = '';
  if (p.startsWith('!')) {
    neg = '!';
    p = p.slice(1);
  }
  // Drop the trailing `/` unconditionally — Syncthing's trailing-slash
  // semantics ("contents only, not the entry") apply REGARDLESS of
  // whether the pattern has embedded slashes (round-2 codex fix; round-1
  // only stripped from non-rooted patterns, leaving `.yarn/cache/` —
  // the one embedded-slash + trailing-slash entry in LIGHTWEIGHT_DEFAULT_IGNORE
  // — emitted in the wrong form). Both rooted (`path/to/dir/`) and
  // non-rooted (`name/`) gitignore forms need the strip to match the
  // gitignore "dir + contents" intent on the Syncthing side.
  //
  // Defensive empty-result check: a degenerate input `/` would strip
  // to '' which is not a valid Syncthing rule. Drop the strip in that
  // edge case so the writer emits `/` verbatim (still bogus, but
  // visible to a debugging user instead of silently disappearing).
  if (p.endsWith('/') && p.length > 1) {
    p = p.slice(0, -1);
  }
  return neg + p;
}

// Build the .stignore content for a workspace. Pure function — no IO.
//
// Inputs:
//   - mode: 'lightweight' | 'full' (passes through to getEffectiveIgnoreLines)
//   - projectRoot: absolute path; getEffectiveIgnoreLines reads
//     .kariignore from here
//   - includeOverrides: iterable (Set / Array) of canonical anchor
//     relPaths. Hard-ignore anchors are silently dropped (defense
//     in depth — the store should never persist them, but if a
//     hand-edit slipped one through we still don't emit a `!` line
//     for it). Invalid anchors (absolute, ..-escape, empty) silently
//     dropped via normalizeAnchor returning null.
//
// Returns: the full .stignore content as a string, with trailing
// newline so concat-with-other-content stays clean.
async function buildStignoreContent({ projectRoot, mode, includeOverrides }) {
  if (!projectRoot) {
    throw new Error('buildStignoreContent: projectRoot is required');
  }
  const lines = [];

  // Header — single comment line; makes it identifiable as ours so
  // a hand-editing user knows it'll be overwritten.
  lines.push('# generated by Kari Desktop — do not edit manually');
  lines.push('');

  // Hard-ignore — always present. getHardIgnoreLines returns the
  // base patterns; we emit them as Syncthing-style globs (the bare
  // patterns from ignore_evaluator are gitignore-style which Syncthing
  // also accepts, but we normalize for consistency).
  lines.push('# Hard-ignore (never syncable — even !-rules below cannot override).');
  for (const pat of getHardIgnoreLines()) {
    lines.push(toStignoreForm(pat));
  }
  lines.push('');

  // Project include overrides — `!`-prefix-first recipe. MUST come
  // BEFORE the denylist; first-match-wins.
  const anchors = [];
  if (includeOverrides) {
    const iter = (typeof includeOverrides[Symbol.iterator] === 'function')
      ? includeOverrides
      : [];
    for (const raw of iter) {
      const a = normalizeAnchor(raw);
      if (!a) continue;
      // Defense in depth: never emit a `!`-rule for a hard-ignore
      // anchor, even if the override store somehow surfaced one
      // (the store rejects them on write but a hand-edited file
      // could slip one through). Without this filter, the resulting
      // .stignore would let Syncthing transport-sync the path even
      // though the matcher's hard-ignore front predicate blocks the
      // snapshot pipeline from including it.
      if (isHardIgnored(a)) continue;
      anchors.push(a);
    }
  }
  // Sort anchors lexically so the output is deterministic (helps
  // tests + makes diffs across mtime-vs-mtime stable).
  anchors.sort();
  if (anchors.length > 0) {
    lines.push('# Project include overrides — re-include carve-outs.');
    for (const anchor of anchors) {
      for (const ln of renderAnchorOverrideLines(anchor)) {
        lines.push(ln);
      }
    }
    lines.push('');
  }

  // Lightweight denylist + user .kariignore — from getEffectiveIgnoreLines.
  // In 'full' mode this is just .kariignore (denylist is empty).
  // In 'lightweight' mode it's denylist first, then .kariignore.
  // Either way it comes AFTER the !-prefix re-includes above.
  const effective = await getEffectiveIgnoreLines({ projectRoot, mode });
  if (effective.length > 0) {
    lines.push('# Effective ignore rules (denylist + .kariignore).');
    for (const ln of effective) {
      lines.push(toStignoreForm(ln));
    }
    lines.push('');
  }

  return lines.join('\n');
}

// Write {projectRoot}/.stignore atomically. Builds the content via
// buildStignoreContent then writes via .tmp + rename so Syncthing
// (which watches .stignore) never reads a half-written file. Caller
// is responsible for deciding WHEN to invoke (typically: before
// bindAndStartDaemon for syncthing-backed workspaces; after every
// override / mode change that affects the effective ignore set).
//
// Idempotency: skips the write entirely when the new content matches
// what's already on disk. Avoids touching .stignore's mtime on no-op
// refreshes, which can otherwise re-trigger Syncthing's folder scan.
//
// Best-effort: returns { ok: boolean, reason?, skipped?: 'unchanged' }.
// Callers should NOT throw on a write failure — daemon's prior
// .stignore is the fallback. The error path is logged at the caller
// (so a single .stignore IO failure doesn't break the bind).
// Sentinel header line used by buildStignoreContent. Lets writeStignoreFile
// detect whether an existing .stignore is Kari-authored (overwrite is
// safe) vs user-authored (back up to .stignore.user-backup-<ts> before
// overwriting — round-1 codex #4).
const KARI_HEADER = '# generated by Kari Desktop';

async function writeStignoreFile({ projectRoot, mode, includeOverrides }) {
  if (!projectRoot) {
    return { ok: false, reason: 'missing_projectRoot' };
  }
  let content;
  try {
    content = await buildStignoreContent({ projectRoot, mode, includeOverrides });
  } catch (err) {
    return { ok: false, reason: 'build_failed', error: String((err && err.message) || err) };
  }
  const stignorePath = path.join(projectRoot, '.stignore');

  // Read prior content for both idempotency check AND user-authored
  // detection. ENOENT → no prior file (first write). Non-ENOENT read
  // errors (EACCES, EBUSY, EIO) REFUSE the overwrite (round-2 codex
  // #2): if we can't see the prior content we can't tell whether
  // it's user-authored, and overwriting unconditionally regresses
  // round-1 #4's data-loss intent. Treat the IPC as a logged
  // best-effort failure; daemon's prior .stignore is the fallback.
  let prior = null;
  try {
    prior = await withTransientRetry(() => fsp.readFile(stignorePath, 'utf8'));
  } catch (err) {
    if (err && err.code === 'ENOENT') {
      // No prior file — first write. Safe to proceed.
    } else {
      console.warn('[stignore_writer] prior-content read failed for ' + stignorePath
        + '; refusing overwrite:', String((err && err.message) || err));
      return {
        ok: false,
        reason: 'prior_read_failed',
        error: String((err && err.message) || err),
      };
    }
  }

  if (prior === content) {
    return { ok: true, skipped: 'unchanged' };
  }

  // Round-1 codex #4: if a prior .stignore exists AND lacks the Kari
  // header, treat it as user-authored. Back it up to a timestamped
  // .user-backup file before overwriting so the user's hand-curated
  // rules are recoverable. The header check distinguishes Kari-owned
  // (overwrite freely) from user-owned (backup first) without needing
  // a separate metadata file.
  if (prior !== null && prior.length > 0 && !prior.startsWith(KARI_HEADER)) {
    const backupPath = stignorePath + '.user-backup-' + new Date().toISOString().replace(/[:.]/g, '-');
    try {
      await fsp.writeFile(backupPath, prior, 'utf8');
      console.warn('[stignore_writer] backed up user-authored .stignore to ' + backupPath);
    } catch (err) {
      // Backup failed — refuse to overwrite. User's original content
      // is the priority over Kari's bind-time write.
      return {
        ok: false,
        reason: 'user_authored_backup_failed',
        error: String((err && err.message) || err),
      };
    }
  }

  // Unique .tmp suffix (round-1 codex #1): a fixed `.tmp` path under
  // concurrent writers can race — two callers writing the same tmp
  // path interleave, then one's unlink-on-error clobbers the other's
  // in-flight tmp. PID + random hex is collision-free across processes
  // and concurrent calls in this process.
  const tmpSuffix = `.tmp.${process.pid}.${crypto.randomBytes(4).toString('hex')}`;
  const tmpPath = stignorePath + tmpSuffix;
  try {
    await fsp.writeFile(tmpPath, content, 'utf8');
    // Rename can transiently fail on Windows when the destination is briefly
    // locked by a concurrent reader/writer (defender, fs cache). Same
    // transient-retry policy as the prior-content read above.
    await withTransientRetry(() => fsp.rename(tmpPath, stignorePath));
    return { ok: true };
  } catch (err) {
    // Best-effort cleanup of our OWN tmp (uniquely-suffixed so we
    // can't clobber a sibling's tmp); ignore failures.
    await fsp.unlink(tmpPath).catch(() => null);
    return { ok: false, reason: 'write_failed', error: String((err && err.message) || err) };
  }
}

module.exports = {
  buildStignoreContent,
  writeStignoreFile,
  renderAnchorOverrideLines,
  normalizeAnchor,
  toStignoreForm,
};
